github.com:
    users:
        rizalynne22:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: rizalynne22
