github.com:
    users:
        rizalynne22:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: rizalynne22
